name: "create-tag"
description: "Creates git tag"

inputs:
  tag:
    description: 'tag to create'
    required: true
  current-tag:
    description: 'current release tag'
    required: true

runs:
  using: composite
  steps:
    - name: echo
      shell: bash
      run: |
        echo "CURRENT RELEASE $CURRENT_RELEASE"
        echo "NEW TAG $TAG"
        echo "CURRENT TAGS:"
        git tag --points-at HEAD
      env:
        TAG: ${{ inputs.tag }}
        CURRENT_RELEASE: ${{ inputs.current-tag }}
    - name: tag
      shell: bash
      run: 'git tag -am "$TAG" $TAG && git push --tags'
      env:
        TAG: ${{ inputs.tag }}
        CURRENT_RELEASE: ${{ inputs.current-tag }}
